fos_rest:
    param_fetcher_listener: force
    view:
        view_response_listener: true
    body_listener: true
    service:
        serializer: null
    format_listener:
        enabled: true
        rules:
            - {
                  path: "^/",
                  priorities: ["json"],
                  fallback_format: "json",
                  prefer_extension: true,
              }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': HTTP_NOT_FOUND
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': HTTP_NOT_FOUND
            'Doctrine\DBAL\Exception\UniqueConstraintViolationException': HTTP_CONFLICT
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
            'Doctrine\DBAL\Exception\UniqueConstraintViolationException': true
